export default{
    myProfile:'My profile',
    apiKeyName:'ReadWrite_allWorkbooks',
    generateAndViewButtonText:'Generate & View',
    apiKeysText:'API keys',
    generateAPIKeyModalTitle:'Generate API key',
    aSpecificWorkbookOptionText:['A specific workbook that I own ...','A specific workbook ...'],
    allWorkbooksThatIOwnText:['All workbooks that I own','All workbooks accessible to me'],
    onlyWorkbook:'Project Plan',
    selectedWorkbookText:'Specific workbook: Project Plan',
    keyType:['Read & Write','Read Only','Write Only'],
    defaultOptionsSelected:['REST API','All workbooks accessible to me'],
    apiKeyModalTitle:"API key generated! Copy your key now.",
    generatedAPIKeyModalText:"Please copy the key and save it somewhere safe.",
    apiKeySuggestion:"For security reasons, we cannot show it you again.",
    modalKeyHeadersText:["Name","Usage","Type","Scope"],
    apiKeysTableTitlesText:["Name","Usage","Type","Entity","Created at","Last used"],
    copyKeyText:'Copy key',
    doneText:'Done',
    entityName:'Specific workbook: Project Plan',
    generateAPIKeys: [['APIRW','REST API','Read & Write',1,'API'],
              ['APIRead','REST API','Read Only',1,'API'],
              ['APIWrite','REST API','Write Only',1,'API'],
              ['ZapierRW','Zapier','Read & Write',0,'ZAPIER'],
              ['ZapierRead','Zapier','Read Only',0,'ZAPIER'],
              ['ZapierWrite','Zapier','Write Only',0,'ZAPIER']],
}
